<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class NasabahTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('nasabahs')->truncate();
        DB::table('nasabah_loans')->truncate();

        $data =
[
            [
                'id' => 1,
                'nik' => '01',
                'nama' => 'Puji',
                'alamat' => 'Desa Depok',
                'no_hp' => '083840462924',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => 'Pedagang Pakian',
                'file_ktp' => 'nasabah_files/5DFADBKGj7px4djbxzKXdxnP1FgFRT3TcEbtD0fx.jpg',
                'file_jaminan' => 'nasabah_files/jrp2JrIhs33aDbE3Sc91qiUCrJ3baMfrf00wptvm.jpg',
                'status' => 'aman',
                'created_at' => '2026-02-09 04:31:50',
                'updated_at' => '2026-02-09 04:31:50',
            ],
            [
                'id' => 2,
                'nik' => '132156888',
                'nama' => 'Ari',
                'alamat' => 'Pegonten',
                'no_hp' => '02356897512',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => 'Proyek',
                'file_ktp' => 'nasabah_files/W8dFU7BjYPfe2alMQEXfMl196gagChsRhh0149sX.jpg',
                'file_jaminan' => 'nasabah_files/Lo1HdSO6pe7yTM9pR14WIqz50E6Ol6kq4hfxBvdn.jpg',
                'status' => 'aman',
                'created_at' => '2026-02-09 04:36:48',
                'updated_at' => '2026-02-09 04:36:48',
            ],
            [
                'id' => 3,
                'nik' => '12548985',
                'nama' => 'Sunarto',
                'alamat' => 'Genengsari',
                'no_hp' => '1245789755',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => 'Pedagang Sayur',
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 04:38:03',
                'updated_at' => '2026-02-09 04:38:03',
            ],
            [
                'id' => 4,
                'nik' => '12486788',
                'nama' => 'Kecus/Doyok',
                'alamat' => 'Kenteng',
                'no_hp' => '2134568855',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => 'Proyek',
                'file_ktp' => 'nasabah_files/M11M8Jbl3vsvbFOaYkHjbJOROtkQLJuEJLRg8QiI.jpg',
                'file_jaminan' => 'nasabah_files/cpYTorF5FoyWLdia2PN6NDIMvgdIRyq6znq9hKs8.jpg',
                'status' => 'aman',
                'created_at' => '2026-02-09 04:38:55',
                'updated_at' => '2026-02-09 04:38:55',
            ],
            [
                'id' => 5,
                'nik' => '122465788',
                'nama' => 'Rani',
                'alamat' => 'Desa Kenteng, Ngancar',
                'no_hp' => '45512588',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => 'nasabah_files/A8ScqLn6FkJNyZB1RhtP8LVcfVOFUYd36SdBlfDj.jpg',
                'file_jaminan' => 'nasabah_files/uCRzl4KLN2gaqcnnrcMkdHuQNX3uHBSebBgIGZ6G.jpg',
                'status' => 'aman',
                'created_at' => '2026-02-09 04:39:44',
                'updated_at' => '2026-02-09 04:39:44',
            ],
            [
                'id' => 6,
                'nik' => '12245878',
                'nama' => 'Suwanto',
                'alamat' => 'Desa Tunggak, Tunggak 2',
                'no_hp' => null,
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => 'nasabah_files/3EmwXk5Mry8tpb94Y0vRUVVG0q4N2wpRycifUB8T.jpg',
                'file_jaminan' => 'nasabah_files/Hdea4hTye2N5uU4PcnxORs2hEibpjIE4lYmmdzqx.jpg',
                'status' => 'aman',
                'created_at' => '2026-02-09 04:40:26',
                'updated_at' => '2026-02-09 04:40:26',
            ],
            [
                'id' => 7,
                'nik' => '125545',
                'nama' => 'Mencis',
                'alamat' => 'Desa Kenteng, Sidomulyo',
                'no_hp' => '122565',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => 'nasabah_files/P27KUlwbyaboGkkPyoGRDinRNs8q2sChVtk6Te5S.jpg',
                'file_jaminan' => 'nasabah_files/GEZVWWmTzDW4fz7eg0fmrAhBDs9jBfubDZdPJ3ms.jpg',
                'status' => 'aman',
                'created_at' => '2026-02-09 04:41:29',
                'updated_at' => '2026-02-09 04:41:29',
            ],
            [
                'id' => 8,
                'nik' => '1234',
                'nama' => 'Suwarti',
                'alamat' => 'Desa Ngrandah',
                'no_hp' => '12685',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => 'Mebel',
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 04:42:23',
                'updated_at' => '2026-02-09 04:42:23',
            ],
            [
                'id' => 9,
                'nik' => '122456',
                'nama' => 'Rina Setiowati',
                'alamat' => 'Desa Tunggak, Kernekan',
                'no_hp' => '8258988',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => 'nasabah_files/Osnk7NTgPZvL605UUaGiXZw7PcV6FnzjbXqgWIMb.jpg',
                'file_jaminan' => 'nasabah_files/wlwuRj2XQox8iQFRxEpJ2qhWuC6YlkjXLkb2YYer.jpg',
                'status' => 'aman',
                'created_at' => '2026-02-09 04:43:26',
                'updated_at' => '2026-02-09 04:43:26',
            ],
            [
                'id' => 10,
                'nik' => '45278525',
                'nama' => 'Supriati',
                'alamat' => 'Desa Sembungharjo, Kanusan',
                'no_hp' => '57283',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => 'nasabah_files/SzqYkSRqq39UmKOba03kvA4rASZU32oBBwQPiU7S.jpg',
                'file_jaminan' => 'nasabah_files/SyMu6Z0imuybnuR3vxZjN0f1zf0iGZZQagLXcmRa.jpg',
                'status' => 'aman',
                'created_at' => '2026-02-09 04:44:32',
                'updated_at' => '2026-02-09 04:44:32',
            ],
            [
                'id' => 11,
                'nik' => '252855287',
                'nama' => 'Purjiyem',
                'alamat' => 'Desa Tunggak, Kramat',
                'no_hp' => '212215465',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => 'nasabah_files/f60iGbpromYhqaZ7XLhubwx4NWZ0J5M7tCzsb6Yy.jpg',
                'file_jaminan' => 'nasabah_files/EHhP9Tak0TMiHVmPzdk0IV40Qbp3K3C7Zjj8mLO6.jpg',
                'status' => 'aman',
                'created_at' => '2026-02-09 04:45:29',
                'updated_at' => '2026-02-09 04:45:29',
            ],
            [
                'id' => 12,
                'nik' => '25285728',
                'nama' => 'Sri Mulyani',
                'alamat' => 'Desa Boloh, Telogo',
                'no_hp' => '252572',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => 'nasabah_files/UcbOIVC6uPXsg9Dk2wX8pSn4jDd09Vz00BKJcTQW.jpg',
                'file_jaminan' => 'nasabah_files/DP0aUWdf5NCrlXqNcC6rJkpJHClksTu0qSGHCoDk.jpg',
                'status' => 'aman',
                'created_at' => '2026-02-09 04:47:41',
                'updated_at' => '2026-02-09 04:47:41',
            ],
            [
                'id' => 13,
                'nik' => '52828',
                'nama' => 'Triana',
                'alamat' => 'Desa Plosoharjo, Bandil',
                'no_hp' => '258225',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => 'nasabah_files/QIRfussb8F4MbSFXA4UF9ooYQ9BFf6Ije4WHgJcA.jpg',
                'file_jaminan' => 'nasabah_files/PGgPT8t09ekrH715CiDGI0QD7d2TOS1Br8vwIx3u.jpg',
                'status' => 'aman',
                'created_at' => '2026-02-09 04:48:40',
                'updated_at' => '2026-02-09 04:48:40',
            ],
            [
                'id' => 14,
                'nik' => '2829862',
                'nama' => 'Murmini',
                'alamat' => 'Desa Genengsari',
                'no_hp' => '285825',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => 'nasabah_files/YxD5KRIpKrq2yFDPBUTqE4hSATdKZp0onZWFDZts.jpg',
                'file_jaminan' => 'nasabah_files/IbQJQIsmLtkKuHaR5bnGjaEUzh3UvCYuXGYLxYLP.jpg',
                'status' => 'aman',
                'created_at' => '2026-02-09 04:52:59',
                'updated_at' => '2026-02-09 04:52:59',
            ],
            [
                'id' => 15,
                'nik' => '2582',
                'nama' => 'Aziz',
                'alamat' => 'Desa Boloh, Kayen',
                'no_hp' => '083840462924',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => 'nasabah_files/TDxEVj8EptAkdq9tjeVjTxCn7Ws8oIeeKQuxDFPX.jpg',
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 04:53:47',
                'updated_at' => '2026-02-09 04:53:47',
            ],
            [
                'id' => 16,
                'nik' => '258285',
                'nama' => 'Endang',
                'alamat' => 'Desa Boloh, Jaren',
                'no_hp' => '122565',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 04:55:06',
                'updated_at' => '2026-02-09 04:55:06',
            ],
            [
                'id' => 17,
                'nik' => '5282',
                'nama' => 'Sri Wahyuni',
                'alamat' => 'Plosoharjo',
                'no_hp' => '122565',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 05:02:30',
                'updated_at' => '2026-02-09 05:02:30',
            ],
            [
                'id' => 18,
                'nik' => '12234',
                'nama' => 'Rasmi',
                'alamat' => 'Desa Tunggak, Clepat',
                'no_hp' => '122565',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 05:03:22',
                'updated_at' => '2026-02-09 05:03:22',
            ],
            [
                'id' => 19,
                'nik' => '1123',
                'nama' => 'Suprih',
                'alamat' => 'Desa Plosoharjo, Kleben',
                'no_hp' => '12235',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 05:04:17',
                'updated_at' => '2026-02-09 05:04:17',
            ],
            [
                'id' => 20,
                'nik' => '13555',
                'nama' => 'Novita Sari',
                'alamat' => 'Desa Kenteng',
                'no_hp' => '25485',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 05:11:30',
                'updated_at' => '2026-02-09 05:11:30',
            ],
            [
                'id' => 21,
                'nik' => '2578',
                'nama' => 'Riki Prasetya',
                'alamat' => 'Desa Kenteng Welar',
                'no_hp' => '122565',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 05:12:15',
                'updated_at' => '2026-02-09 05:12:15',
            ],
            [
                'id' => 22,
                'nik' => '58448',
                'nama' => 'Tri Gangga',
                'alamat' => 'Desa Karangharjo, Legundi',
                'no_hp' => '122565',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 05:14:36',
                'updated_at' => '2026-02-09 05:14:36',
            ],
            [
                'id' => 23,
                'nik' => '2158455',
                'nama' => 'Umar',
                'alamat' => 'Desa Nambuhan, Jetis',
                'no_hp' => '122565',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 05:15:12',
                'updated_at' => '2026-02-09 05:15:12',
            ],
            [
                'id' => 24,
                'nik' => '48864',
                'nama' => 'Gudel',
                'alamat' => 'Desa Tunggak, Tunggak 2',
                'no_hp' => '122565',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => 'Mandor',
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 05:15:51',
                'updated_at' => '2026-02-09 05:15:51',
            ],
            [
                'id' => 25,
                'nik' => '86',
                'nama' => 'Suparmi',
                'alamat' => 'Desa Boloh',
                'no_hp' => '122565',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 05:16:39',
                'updated_at' => '2026-02-09 05:16:39',
            ],
            [
                'id' => 26,
                'nik' => '8448',
                'nama' => 'Darmini/Dwik',
                'alamat' => 'Desa Tambirerjo, Sanggeh',
                'no_hp' => '122565',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 05:17:11',
                'updated_at' => '2026-02-09 05:17:11',
            ],
            [
                'id' => 27,
                'nik' => '78',
                'nama' => 'Aguswanto',
                'alamat' => 'Desa Plosoharjo, Pondok, RT 01, RW 06',
                'no_hp' => '122565',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 05:17:46',
                'updated_at' => '2026-02-09 05:17:46',
            ],
            [
                'id' => 28,
                'nik' => '98448',
                'nama' => 'Anita',
                'alamat' => 'Desa Plosoharjo, Bandil, RT 05, RW 010',
                'no_hp' => null,
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 05:18:27',
                'updated_at' => '2026-02-09 05:18:27',
            ],
            [
                'id' => 29,
                'nik' => '796',
                'nama' => 'Sulastri',
                'alamat' => 'Desa Plosoharjo, Bandil, RT 07, RW 10',
                'no_hp' => null,
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 05:19:03',
                'updated_at' => '2026-02-09 05:19:03',
            ],
            [
                'id' => 30,
                'nik' => '84684',
                'nama' => 'Hendri',
                'alamat' => 'Desa Kenteng, Sumberagung',
                'no_hp' => null,
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 05:19:30',
                'updated_at' => '2026-02-09 05:19:30',
            ],
            [
                'id' => 31,
                'nik' => '78448',
                'nama' => 'Ceplok',
                'alamat' => 'Desa Genengsari',
                'no_hp' => '122565',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 05:20:01',
                'updated_at' => '2026-02-09 05:20:01',
            ],
            [
                'id' => 32,
                'nik' => '45',
                'nama' => 'Sriyatun',
                'alamat' => 'Desa Kenteng, Welar, RT 03, RW 01',
                'no_hp' => '122565',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 05:20:54',
                'updated_at' => '2026-02-09 05:20:54',
            ],
            [
                'id' => 33,
                'nik' => '789',
                'nama' => 'Wito',
                'alamat' => 'Desa Tunggak, Clepat',
                'no_hp' => '122565',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 05:21:18',
                'updated_at' => '2026-02-09 05:21:18',
            ],
            [
                'id' => 34,
                'nik' => '458',
                'nama' => 'Rizal Romadhon',
                'alamat' => 'Desa Tambirejo',
                'no_hp' => '122565',
                'pekerjaan' => 'WiraSwasta',
                'usaha' => null,
                'file_ktp' => null,
                'file_jaminan' => null,
                'status' => 'aman',
                'created_at' => '2026-02-09 05:22:03',
                'updated_at' => '2026-02-09 05:22:03',
            ]
        ]
;

        DB::table('nasabahs')->insert($data);

        Schema::enableForeignKeyConstraints();
    }
}
